import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header__logo from '../components/Header__logo/Header__logo'
import Navbar from '../components/Navbar/Navbar'
import Content from '../components/Content/Content'
// import Particlebg from '../components/Particles/Particlebg'

export default function Home() {
  return (
    <>
      <Head>
        <title>SpaceX</title>
        <meta name="description" content="Generated by create next app" />
     
      </Head>
      {/* <Particlebg/> */}
       <Header__logo/>
       <Navbar/>
       <Content/>
       
    </>
  )
}
